---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: shoe-customers
  namespace: confluent-demo
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    name: shoe-customers
    # connector.class: io.confluent.connect.jms.IbmMqSinkConnector
    kafka.topic: shoe-customers
    quickstart: shoe_customers
    max.interval: "10000"
    # Should be inherited from the connect worker
    # key.converter: io.confluent.connect.avro.AvroConverter
    # value.converter: io.confluent.connect.avro.AvroConverter
    # key.converter.schema.registry.ssl.truststore.location: "/mnt/sslcerts/tls-kraft/truststore.p12"
    # key.converter.schema.registry.ssl.truststore.password: "mystorepassword"
    # key.converter.schema.registry.url: https://schemaregistry.confluent-demo.svc.cluster.local:8081
    # value.converter.schema.registry.ssl.truststore.location: "/mnt/sslcerts/tls-kraft/truststore.p12"
    # value.converter.schema.registry.ssl.truststore.password: "mystorepassword"
    # value.converter.schema.registry.url: https://schemaregistry.confluent-demo.svc.cluster.local:8081