--- # Kafka Brokers
# Listeners:
# 9071: INTERNAL (SASL_SSL, LDAP)
# 9092: EXTERNAL (SASL_SSL, LDAP) - exposed externally on port 443
# 9072: REPLICATION (MTLS)
# 9073: TOKEN (SASL_SSL, OAUTHBEARER w/ MDS)

apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: ${NAMESPACE}
spec:
  replicas: 3
  # authorization:
  #   superUsers:
  #     - User:kraft
  #     - User:mds
  #     - User:kafka
  #     - User:operator
  #     # - User:ssologin
  #   type: rbac
  image:
    application: confluentinc/cp-server:${CONFLUENT_PLATFORM_VERSION}
    init: confluentinc/confluent-init-container:${CFK_INIT_CONTAINER_VERSION}
  dataVolumeCapacity: 5Gi
  listeners:
    # INTERNAL: 9071 (mTLS))
    internal:
      authentication:
        mtls:
          sslClientAuthentication: required
        type: mtls
      tls:
        enabled: true
    # EXTERNAL: 9092 (mTLS > OIDC)
    external:
      # externalAccess:
      #   type: staticForHostBasedRouting
      #   staticForHostBasedRouting:
      #     port: 443
      #     domain: 127-0-0-1.nip.io
      #     brokerPrefix: kafka-
      # authentication:
      #   mtls:
      #     sslClientAuthentication: required
      #   type: mtls
      authentication:
        type: oauth
        jaasConfig:
          secretRef: oauth-jaas
        # https://keycloak.${KEYCLOAK_NAMESPACE}.svc.cluster.local:8443//realms/confluent/.well-known/openid-configuration
        oauthSettings:
          subClaimName: client_id
          expectedIssuer: http://keycloak.${KEYCLOAK_NAMESPACE}.svc.cluster.local:8080/realms/confluent
          jwksEndpointUri: http://keycloak.${KEYCLOAK_NAMESPACE}.svc.cluster.local:8080/realms/confluent/protocol/openid-connect/certs
          tokenEndpointUri: http://keycloak.${KEYCLOAK_NAMESPACE}.svc.cluster.local:8080/realms/confluent/protocol/openid-connect/token
      tls:
        enabled: true
    # REPLICATION: 9072 (mTLS)
    replication:
      authentication:
        mtls:
          sslClientAuthentication: required
        type: mtls
      tls:
        enabled: true
    # TOKEN: 9073?
  metricReporter:
    enabled: false
  # services:
  #   mds:
  #     provider:
  #       ldap:
  #         address: ldap://ldap.${NAMESPACE}.svc.cluster.local:389
  #         authentication:
  #           simple:
  #             secretRef: admin-ldap-client
  #           type: simple
  #         configurations:
  #           groupNameAttribute: cn
  #           groupObjectClass: Group
  #           groupMemberAttribute: member
  #           groupMemberAttributePattern: CN=(.*),DC=confluent,DC=justinrlee,DC=io
  #           groupSearchBase: dc=confluent,dc=justinrlee,dc=io
  #           groupSearchScope: 2
  #           userNameAttribute: cn
  #           userMemberOfAttributePattern: CN=(.*),DC=confluent,DC=justinrlee,DC=io
  #           userObjectClass: inetOrgPerson
  #           userSearchBase: dc=confluent,dc=justinrlee,dc=io
  #           userSearchScope: 2
  #         tls:
  #           enabled: true
  #       type: ldap
  #     tls:
  #       enabled: true
  #     tokenKeyPair:
  #       secretRef: mds-token
  dependencies:
    kRaftController:
      controllerListener:
        tls:
          enabled: true
        authentication:
          type: mtls
      clusterRef:
        name: kraft
    # metricsClient:
    #   url: https://controlcenter.${NAMESPACE}.svc.cluster.local:9090
    #   tls:
    #     enabled: true
    #     secretRef: tls-controlcenter
    # kafkaRest:
    #   authentication:
    #     bearer:
    #       secretRef: kafka-ldap-client
    #     type: bearer
    #   # tls:
    #   #   enabled: true
    #   #   secretRef: tls-kafka
    # schemaRegistry:
    #   authentication:
    #     type: basic
    #     basic:
    #       secretRef: rest-client
    #   tls:
    #     enabled: true
    #     secretRef: tls-kraft
    #   url: https://schemaregistry.${NAMESPACE}.svc.cluster.local:8081
  tls:
    secretRef: tls-kafka
