---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: manual-admin
  namespace: ${NAMESPACE}
spec:
  principal:
    # name: 8b0e6985-da9a-49d2-9205-fcf4735c81f4
    # type: user
    name: "/administrators"
    type: group
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: manual-admin-connect
  namespace: ${NAMESPACE}
spec:
  clustersScopeByIds:
    connectClusterId: confluent-demo.connect
  principal:
    name: "/administrators"
    type: group
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: manual-admin-sr
  namespace: ${NAMESPACE}
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_confluent-demo
  principal:
    name: "/administrators"
    type: group
  role: SystemAdmin
