name: ldap
image: osixia/openldap:1.5.0
tls:
  enabled: true
  fullchain: |-
  privkey: |-
  cacerts: |-

env:
  LDAP_ORGANISATION: "Test Inc."
  LDAP_DOMAIN: "test.com"
  LDAP_ADMIN_PASSWORD: "confluentrox"
  LDAP_CONFIG_PASSWORD: "confluentconfigrox"
  LDAP_READONLY_USER: "true"
  LDAP_READONLY_USER_USERNAME: "mds"
  LDAP_READONLY_USER_PASSWORD: "Developer!"
  LDAP_BASE_DN: "dc=test,dc=com"

# organizationalRoles cannot be part of groups; are used for CP components
# mds (created automatically)
# kraft
# kafka
# schemaregistry
# connect
# controlcenter

# OUs:
# users
# groups

# users:
#   admin (part of all groups)
#   developer
#   alice (admin)
#   brian (developer)
#   charlie (readonly)

# groups:
#   administrators
#   developers
#   readonlyusers
#   # TBD

# Adding integer before ldif name to allow sequence order.
ldifs:
  00_kraft.ldif: |-
    dn: cn=kraft,{{ LDAP_BASE_DN }}
    userPassword: kraft-secret
    description: kraft user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: kraft

  01_kafka.ldif: |-
    dn: cn=kafka,{{ LDAP_BASE_DN }}
    userPassword: kafka-secret
    description: kafka user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: kafka

  02_schemaregistry.ldif: |-
    dn: cn=schemaregistry,{{ LDAP_BASE_DN }}
    userPassword: schemaregistry-secret
    description: schema registry user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: schemaregistry

  03_conect.ldif: |-
    dn: cn=connect,{{ LDAP_BASE_DN }}
    userPassword: connect-secret
    description: connect user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: connect

  04_controlcenter.ldif: |-
    dn: cn=controlcenter,{{ LDAP_BASE_DN }}
    userPassword: controlcenter-secret
    description: controlcenter user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: controlcenter

  10_ou_users.ldif: |-
    dn: ou=users,{{ LDAP_BASE_DN }}
    objectClass: organizationalUnit
    ou: Users

  11_ou_groups.ldif: |-
    dn: ou=groups,{{ LDAP_BASE_DN }}
    objectClass: organizationalUnit
    ou: Groups

  15_user_admin.ldif:  |-
    dn: cn=admin,ou=users,{{ LDAP_BASE_DN }}
    objectClass: inetOrgPerson
    uid: admin
    sn: TheAdmin
    givenName: Admin
    cn: admin
    displayName: Admin TheAdmin
    userPassword: admin-secret
    ou: Users

  16_user_developer.ldif:  |-
    dn: cn=developer,ou=users,{{ LDAP_BASE_DN }}
    objectClass: inetOrgPerson
    uid: developer
    sn: Guy
    givenName: Developer
    cn: developer
    displayName: Developer Guy
    userPassword: developer-secret
    ou: Users

  17_user_alice.ldif:  |-
    dn: cn=alice,ou=users,{{ LDAP_BASE_DN }}
    objectClass: inetOrgPerson
    uid: alice
    sn: LookingGlass
    givenName: Alice
    cn: alice
    displayName: Alice LookingGlass
    userPassword: alice-secret
    ou: Users

  18_user_brian.ldif:  |-
    dn: cn=brian,ou=users,{{ LDAP_BASE_DN }}
    objectClass: inetOrgPerson
    uid: brian
    sn: SomethingNeat
    givenName: Brian
    cn: brian
    displayName: Brian SomethingNeat
    userPassword: brian-secret
    ou: Users

  19_user_charlie.ldif:  |-
    dn: cn=charlie,ou=users,{{ LDAP_BASE_DN }}
    objectClass: inetOrgPerson
    uid: charlie
    sn: TheUnicorn
    givenName: Charlie
    cn: charlie
    displayName: Charlie TheUnicorn
    userPassword: charlie-secret
    ou: Users

  20_group_administrators.ldif: |-
    dn: cn=administrators,ou=groups,{{ LDAP_BASE_DN }}
    objectClass: top
    objectClass: groupOfNames
    cn: administrators
    member: cn=admin,ou=users,dc=test,dc=com
    member: cn=alice,ou=users,dc=test,dc=com
    ou: Groups

  21_group_developers.ldif: |-
    dn: cn=developers,ou=groups,{{ LDAP_BASE_DN }}
    objectClass: top
    objectClass: groupOfNames
    cn: developers
    member: cn=developer,ou=users,{{ LDAP_BASE_DN }}
    member: cn=brian,ou=users,{{ LDAP_BASE_DN }}
    ou: Groups

  22_group_readonlyusers.ldif: |-
    dn: cn=readonlyusers,ou=groups,{{ LDAP_BASE_DN }}
    objectClass: top
    objectClass: groupOfNames
    cn: readonlyusers
    member: cn=charlie,ou=users,{{ LDAP_BASE_DN }}
    ou: Groups